basePath: /
definitions:
  src_server_http_v1.UrlShortenerRequest:
    properties:
      url:
        type: string
    type: object
  src_server_http_v1.UrlShortenerResponse:
    properties:
      alias:
        type: string
      expire_time:
        type: string
    type: object
  src_server_http_v1.UrlsListResponse:
    properties:
      alias:
        type: string
      expires:
        type: string
      url:
        type: string
    type: object
  src_server_http_v1.urlStatsResponse:
    properties:
      clicks:
        type: integer
      last_access:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Url-Shortener API
  version: "1.0"
paths:
  /api/v1/{link}:
    delete:
      description: Запрос на удаление короткой ссылки.
      parameters:
      - description: Алиас короткой ссылки
        in: path
        name: link
        required: true
        type: string
      responses:
        "204":
          description: Успешное удаление
        "400":
          description: Некорректный алиас
          schema:
            type: string
        "404":
          description: Короткая ссылка не найдена
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Удаления короткой ссылки.
      tags:
      - Удаление
    get:
      description: Метод перенаправляет пользователя на оригинальный URL, связанный
        с указанной короткой ссылкой.
      parameters:
      - description: Алиас короткой ссылки
        in: path
        name: link
        required: true
        type: string
      responses:
        "302":
          description: Успешное перенаправление
        "400":
          description: Короткая ссылка истекла или недействительна
          schema:
            type: string
        "404":
          description: Оригинальный URL не найден
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Перенаправление на оригинальный URL
      tags:
      - Короткие ссылки
  /api/v1/{link}/stats:
    get:
      description: Метод возвращает статистику по указанной короткой ссылке (количество
        переходов и последнее время доступа).
      parameters:
      - description: Алиас короткой ссылки
        in: path
        name: link
        required: true
        type: string
      responses:
        "200":
          description: Успешный ответ со статистикой
          schema:
            $ref: '#/definitions/src_server_http_v1.urlStatsResponse'
        "400":
          description: Некорректный алиас
          schema:
            type: string
        "404":
          description: Короткая ссылка не найдена
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получение статистики короткой ссылки
      tags:
      - Короткие ссылки
  /api/v1/shortener:
    get:
      description: Метод возвращает список всех коротких ссылок с их данными (оригинальный
        URL, алиас и срок действия).
      produces:
      - application/json
      responses:
        "200":
          description: Список коротких ссылок
          schema:
            items:
              $ref: '#/definitions/src_server_http_v1.UrlsListResponse'
            type: array
        "500":
          description: Ошибка на стороне сервера
          schema:
            type: string
      summary: Получение списка всех коротких ссылок
      tags:
      - Короткие ссылки
    post:
      consumes:
      - application/json
      description: Метод принимает URL и возвращает короткую ссылку.
      parameters:
      - description: Данные для сокращения URL
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/src_server_http_v1.UrlShortenerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Успешный ответ с созданной короткой ссылкой
          schema:
            $ref: '#/definitions/src_server_http_v1.UrlShortenerResponse'
        "400":
          description: Некорректный запрос или данные
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Создание короткой ссылки
      tags:
      - Короткие ссылки
swagger: "2.0"
