basePath: /
host: localhost:8080
info:
  contact: {}
  title: Url-Shortener API
  version: "1.0"
paths:
  /api/v1/{link}:
    delete:
      description: Запрос на удаление короткой ссылки.
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: удаления короткой ссылки.
      tags:
      - Удаление
swagger: "2.0"
